# Generated by Django 2.2.19 on 2023-01-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0002_auto_20230112_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(max_length=201),
        ),
    ]
